### ISSUE TITLE
Support for private repos?

### ISSUE THREAD

**Issue by mikemassari** [noxify/gridsome-source-git#7]
Hey! Thanks for this plugin. 

Would it be possible to add support for private repositories with an access_token authentication? 

Something similar to what the [gatsby-source-github](https://github.com/mosch/gatsby-source-github)  plugin does

**Comment by noxify** [comment]
Hi @Michelemassari 

Thanks for the request.

Based on the `gitnode` docs, it should be possible.
I will check which steps are required to enable it in the package.

Regards,
Marcus

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by noxify** [comment]
Hey @Michelemassari,

I have pushed a new release, which supports now private repositories.
https://github.com/noxify/gridsome-source-git/releases/tag/v2.0.0

If something isn't working than expected, feel free to open an issue :)

Thanks!

Regards,
Marcus

**Comment by mikemassari** [comment]
Thanks so much Marcus,

I'll have a look over the weekend
